all:
	g++ Pratica001.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica001:
	g++ Pratica001.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica002:
	g++ Pratica002.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica003:
	g++ Pratica003.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica004:
	g++ Pratica004.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica005:
	g++ Pratica005.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica006:
	g++ Pratica006.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica007:
	g++ Pratica007.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica008:
	g++ Pratica008.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica009:
	g++ Pratica009.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica010:
	g++ Pratica010.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica011:
	g++ Pratica011.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica012:
	g++ Pratica012.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica013:
	g++ Pratica013.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica014:
	g++ Pratica014.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica015:
	g++ Pratica015.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica016:
	g++ Pratica016.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica017:
	g++ Pratica017.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica018:
	g++ Pratica018.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica019:
	g++ Pratica019.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica020:
	g++ Pratica020.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica021:
	g++ Pratica021.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica022:
	g++ Pratica022.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica023:
	g++ Pratica023.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica024:
	g++ Pratica024.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica025:
	g++ Pratica025.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica026:
	g++ Pratica026.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica027:
	g++ Pratica027.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica028:
	g++ Pratica028.cpp -o pratica -lglut -lGL -lGLU -lm -lSOIL
	./pratica
Pratica029:
	g++ Pratica029.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm -lSOIL
	./pratica
Pratica030:
	g++ Pratica030.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica031:
	g++ Pratica031.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica032:
	g++ Pratica032.cpp -o pratica -lX11 -lXi -lglut -lGL -lGLU -lm
	./pratica
Pratica034:
	g++ Pratica034.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
Pratica035:
	g++ Pratica035.cpp -o pratica -lglut -lGL -lGLU -lm 
	./pratica
