all:
	g++ forms003.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms001:
	g++ forms001.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
forms002:
	g++ forms002.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
forms003:
	g++ forms003.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms004:
	g++ forms004.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms005:
	g++ forms005.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms006:
	g++ forms006.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms007:
	g++ forms007.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms008:
	g++ forms008.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms009:
	g++ forms009.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms010:
	g++ forms010.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms011:
	g++ forms011.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms012:
	g++ forms012.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms013:
	g++ forms013.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms014:
	g++ forms014.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms015:
	g++ forms015.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms016:
	g++ forms016.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms017:
	g++ forms017.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms018:
	g++ forms018.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms019:
	g++ forms019.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms020:
	g++ forms020.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica