all:
	g++ forms003.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms001:
	g++ forms001.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
forms002:
	g++ forms002.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
forms003:
	g++ forms003.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms004:
	g++ forms004.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms005:
	g++ forms005.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms006:
	g++ forms006.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms007:
	g++ forms007.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms008:
	g++ forms008.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica
forms009:
	g++ forms009.cpp -o pratica -lglut -lGL -lGLU -lm -std=c++11
	./pratica