all:
	g++ forms001.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
forms001:
	g++ forms001.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
forms002:
	g++ forms002.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica
forms003:
	g++ forms003.cpp -o pratica -lglut -lGL -lGLU -lm
	./pratica